import {useRef,useState} from 'react';
import {useDispatch,useSelector} from 'react-redux';
import {runIntake,saveComplaint,reset} from '../store';
import {api} from '../services/api';
import {FlaskConical,Paperclip,Send,Check,ShieldCheck,FileText,UserRound,Sparkles} from 'lucide-react';

const groups=[
  ['1. Origin & Customer Details',[['source','Complaint Source'],['customer_name','Customer Name']]],
  ['2. Product & Batch Identification',[['product_name','Product Name'],['product_strength','Product Strength / Grade'],['batch_number','Batch / Lot Number'],['affected_quantity','Affected Quantity'],['manufacturing_date','Manufacturing Date'],['expiry_date','Expiry Date']]],
  ['3. Facility & Material Impact',[['originating_site','Originating Site Block'],['impacted_materials','Impacted Non-Product Materials (NPM)']]],
  ['4. Defect Analysis',[['complaint_type','Complaint Category','wide'],['description','Complaint Description','wide area']]],
];
const label=name=>name.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function LogComplaint(){
  const dispatch=useDispatch(),form=useSelector(s=>s.complaint.form),loading=useSelector(s=>s.complaint.loading),error=useSelector(s=>s.complaint.error);
  const [message,setMessage]=useState(''),[messages,setMessages]=useState([{role:'assistant',kind:'welcome',text:'Ready to process new complaints. Paste the customer email, describe the issue, or upload a complaint report. I’ll extract the facts and run an initial risk assessment.'}]),[notice,setNotice]=useState(''),[dragging,setDragging]=useState(false); const fileInput=useRef();
  const ready=['customer_name','product_name','batch_number','description'].every(key=>form[key]);
  async function process(text,type='text',fileName){const clean=text.trim();if(!clean||loading)return;setNotice('');setMessages(list=>[...list,{role:'user',text:fileName?'':clean,fileName}]);setMessage('');try{const result=await dispatch(runIntake({text:clean,type,currentComplaint:form})).unwrap();setMessages(list=>[...list,{role:'assistant',text:result.summary,updates:result.updated_fields}])}catch(err){setMessages(list=>[...list,{role:'assistant',error:true,text:err.message||'I could not process that complaint. Please try again.'}])}}
  async function handleFile(file){if(!file)return;setDragging(false);setNotice('Extracting document text…');try{const extracted=await api.extract(file);setNotice('');await process(extracted.text,'document',file.name)}catch(err){setNotice(err.message||'The document could not be read.')}}
  async function commit(){if(!ready)return;try{const saved=await dispatch(saveComplaint(form)).unwrap();setNotice(`Complaint ${saved.complaint_number} was committed to the QMS ledger.`);setMessages([{role:'assistant',kind:'welcome',text:'Complaint committed successfully. You can start a new complaint whenever you are ready.'}]);dispatch(reset())}catch(err){setNotice(err.message||'Unable to commit the complaint.')}}
  return <section className="complaint-page"><div className="complaint-workspace"><div className="ledger"><div className="ledger-title"><div><h1>Log Customer Complaint</h1><p>API &amp; FDF Quality Assurance Module</p></div><span className={ready?'commit-state ready':'commit-state'}><i/> {ready?'Ready to Commit':'Pending Triage'}</span></div>{error&&<div className="alert">{error}</div>}
    {groups.map(([heading,fields])=><section className="ledger-group" key={heading}><h2>{heading}</h2><div className="ledger-fields">{fields.map(([name,title,kind=''])=><label className={kind} key={name}>{title}<div className={`read-value ${!form[name]?'empty-value':''}`}>{form[name]||'Awaiting AI extraction…'}</div></label>)}</div></section>)}
    <section className="risk-card"><div className="risk-heading"><ShieldCheck size={22}/><b>AI copilot risk assessment</b></div><div className="risk-fields"><label>Severity (Suggested)<div className="read-value">{form.severity||'Awaiting assessment…'}</div></label><label>Suggested Next Action<div className="read-value">{form.suggested_next_action||'Awaiting assessment…'}</div></label><label className="wide">Initial Risk Assessment<div className="read-value risk-reason">{form.initial_risk_assessment||'The copilot will assess the reported facts after intake.'}</div></label></div></section><button className="commit-button" disabled={!ready||loading} onClick={commit}><Check size={19}/>{loading?'Processing complaint…':'Commit to QMS Ledger'}</button>{notice&&<div className="commit-notice">{notice}</div>}</div>
    <aside className="copilot-panel"><div className="copilot-header"><FlaskConical size={25}/><div><b>AIVOA Copilot</b><small>Drop complaint files or paste text below.</small></div><span className="online"/></div><div className="conversation">{messages.map((item,index)=>item.role==='user'?<div className={`user-message ${item.fileName?'attachment-message':''}`} key={index}>{item.fileName?<span className="file-chip"><FileText size={19}/><span>{item.fileName}<small>Complaint document</small></span></span>:item.text}<UserRound size={18}/></div>:<div className={`assistant-message ${item.error?'error-message':''}`} key={index}><span className="message-icon">{item.kind==='welcome'?<Sparkles size={19}/>:<Check size={18}/>}</span><p>{item.text}</p>{item.updates?.length>0&&<small>Updated: {item.updates.map(label).join(', ')}</small>}</div>)}</div><div className={`message-box ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();handleFile(e.dataTransfer.files[0])}}><button className="attach" aria-label="Attach complaint file" onClick={()=>fileInput.current?.click()}><Paperclip size={24}/></button><input ref={fileInput} hidden type="file" accept=".pdf,.docx,.txt,.eml" onChange={e=>handleFile(e.target.files?.[0])}/><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();process(message)}}} placeholder="Type a message or paste a complaint…"/><button className="send-message" disabled={!message.trim()||loading} onClick={()=>process(message)}><Send size={19}/></button></div><div className="copilot-footer">Powered by LangGraph</div></aside></div></section>
}
